using System.Diagnostics;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;

namespace Moniswitch;

internal static partial class DeskflowBridge
{
    [GeneratedRegex(@"[^A-Za-z0-9._-]")]
    private static partial Regex UnsafeScreenNameCharacters();

    public static string? FindExecutable()
    {
        var candidates = new[]
        {
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "Deskflow", "deskflow-core.exe"),
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Programs", "Deskflow", "deskflow-core.exe"),
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Deskflow", "deskflow-core.exe")
        };

        return candidates.FirstOrDefault(File.Exists);
    }

    public static string GenerateServerConfiguration(
        string windowsScreenName,
        string linuxScreenName,
        HotkeyBinding hotkey)
    {
        var windows = SanitizeScreenName(windowsScreenName, "windows-pc");
        var linux = SanitizeScreenName(linuxScreenName, "linux-pc");

        // Both right edges lead to the other computer, making
        // switchInDirection(right) a deterministic two-machine toggle.
        var text = new StringBuilder();
        text.AppendLine("# Generated by Moniswitch. Deskflow remains a separate GPL-2.0 program.");
        text.AppendLine("section: screens");
        text.AppendLine($"    {windows}:");
        text.AppendLine($"    {linux}:");
        text.AppendLine("end");
        text.AppendLine();
        text.AppendLine("section: links");
        text.AppendLine($"    {windows}:");
        text.AppendLine($"        left = {linux}");
        text.AppendLine($"        right = {linux}");
        text.AppendLine($"    {linux}:");
        text.AppendLine($"        left = {windows}");
        text.AppendLine($"        right = {windows}");
        text.AppendLine("end");
        text.AppendLine();
        text.AppendLine("section: options");
        text.AppendLine("    switchDelay = 250");
        text.AppendLine("    clipboardSharing = true");
        text.AppendLine($"    keystroke({hotkey.DeskflowText}) = switchInDirection(right)");
        text.AppendLine("end");
        return text.ToString();
    }

    public static string WriteServerConfiguration(
        string directoryPath,
        string windowsScreenName,
        string linuxScreenName,
        HotkeyBinding hotkey)
    {
        Directory.CreateDirectory(directoryPath);
        var path = Path.Combine(directoryPath, "deskflow-server.conf");
        File.WriteAllText(path, GenerateServerConfiguration(windowsScreenName, linuxScreenName, hotkey));
        return path;
    }

    public static DeskflowServerController? StartServerIfEnabled(
        InputSharingSettings settings,
        string settingsDirectory,
        HotkeyBinding hotkey)
    {
        if (!settings.Enabled)
        {
            return null;
        }

        try
        {
            var executable = settings.DeskflowExecutablePath;
            if (string.IsNullOrWhiteSpace(executable) || !File.Exists(executable))
            {
                executable = FindExecutable();
            }

            if (string.IsNullOrWhiteSpace(executable))
            {
                return DeskflowServerController.Unavailable("Input sharing: Deskflow not found");
            }

            var deskflowDirectory = Path.Combine(settingsDirectory, "deskflow");
            var serverConfiguration = WriteServerConfiguration(
                deskflowDirectory,
                settings.WindowsScreenName,
                settings.LinuxScreenName,
                hotkey);
            var coreSettings = Path.Combine(deskflowDirectory, "Deskflow.conf");
            EnsureCoreSettings(coreSettings, deskflowDirectory, settings.WindowsScreenName, serverConfiguration);
            OptimizeCoreSettings(coreSettings);
            return DeskflowServerController.StartOrAttach(executable, coreSettings, serverConfiguration);
        }
        catch (Exception exception)
        {
            return DeskflowServerController.Unavailable($"Input sharing: {exception.Message}");
        }
    }

    public static string? TryGetServerFingerprint(string settingsDirectory)
    {
        var certificatePath = Path.Combine(settingsDirectory, "deskflow", "tls", "deskflow.pem");
        if (!File.Exists(certificatePath))
        {
            return null;
        }

        try
        {
            using var certificate = X509Certificate2.CreateFromPemFile(certificatePath);
            return certificate.GetCertHashString(HashAlgorithmName.SHA256);
        }
        catch
        {
            return null;
        }
    }

    private static string SanitizeScreenName(string value, string fallback)
    {
        var sanitized = UnsafeScreenNameCharacters().Replace(value.Trim(), "-");
        return string.IsNullOrWhiteSpace(sanitized) ? fallback : sanitized;
    }

    internal static void EnsureCoreSettings(
        string coreSettings,
        string deskflowDirectory,
        string windowsScreenName,
        string serverConfiguration)
    {
        if (File.Exists(coreSettings))
        {
            return;
        }

        var tlsDirectory = Path.Combine(deskflowDirectory, "tls");
        var certificatePath = Path.Combine(tlsDirectory, "deskflow.pem");
        Directory.CreateDirectory(tlsDirectory);
        if (!File.Exists(certificatePath))
        {
            WriteCertificate(certificatePath);
        }

        var windows = SanitizeScreenName(windowsScreenName, "windows-pc");
        var certificate = IniPath(certificatePath);
        var serverConfig = IniPath(serverConfiguration);
        var logPath = IniPath(Path.Combine(deskflowDirectory, "deskflow-server.log"));
        var text = new StringBuilder();
        text.AppendLine("[core]");
        text.AppendLine($"computerName={windows}");
        text.AppendLine("coreMode=2");
        text.AppendLine("port=24800");
        text.AppendLine("processMode=1");
        text.AppendLine("startedBefore=true");
        text.AppendLine("useHooks=true");
        text.AppendLine();
        text.AppendLine("[gui]");
        text.AppendLine("autoHide=true");
        text.AppendLine("closeToTray=true");
        text.AppendLine("enableUpdateCheck=false");
        text.AppendLine();
        text.AppendLine("[log]");
        text.AppendLine($"file={logPath}");
        text.AppendLine("level=WARNING");
        text.AppendLine("toFile=false");
        text.AppendLine();
        text.AppendLine("[security]");
        text.AppendLine($"certificate={certificate}");
        // Waynergy pins this server certificate. Client-fingerprint prompts
        // require Deskflow's GUI, so the headless server accepts the configured
        // client on the trusted LAN instead of adding another resident process.
        text.AppendLine("checkPeerFingerprints=false");
        text.AppendLine("keySize=3072");
        text.AppendLine("tlsEnabled=true");
        text.AppendLine();
        text.AppendLine("[server]");
        text.AppendLine("externalConfig=true");
        text.AppendLine($"externalConfigFile={serverConfig}");
        File.WriteAllText(coreSettings, text.ToString());
    }

    private static void WriteCertificate(string path)
    {
        using var rsa = RSA.Create(3072);
        var request = new CertificateRequest(
            "CN=Moniswitch Deskflow",
            rsa,
            HashAlgorithmName.SHA256,
            RSASignaturePadding.Pkcs1);
        request.CertificateExtensions.Add(
            new X509BasicConstraintsExtension(false, false, 0, critical: false));
        request.CertificateExtensions.Add(
            new X509KeyUsageExtension(
                X509KeyUsageFlags.DigitalSignature | X509KeyUsageFlags.KeyEncipherment,
                critical: true));
        request.CertificateExtensions.Add(
            new X509SubjectKeyIdentifierExtension(request.PublicKey, critical: false));

        using var certificate = request.CreateSelfSigned(
            DateTimeOffset.UtcNow.AddDays(-1),
            DateTimeOffset.UtcNow.AddYears(10));
        File.WriteAllText(
            path,
            rsa.ExportPkcs8PrivateKeyPem() + Environment.NewLine + certificate.ExportCertificatePem());
    }

    private static string IniPath(string path) => path.Replace('\\', '/');

    private static void OptimizeCoreSettings(string path)
    {
        var lines = File.ReadAllLines(path);
        var inLogSection = false;
        var changed = false;

        for (var index = 0; index < lines.Length; index++)
        {
            var trimmed = lines[index].Trim();
            if (trimmed.StartsWith('[') && trimmed.EndsWith(']'))
            {
                inLogSection = string.Equals(trimmed, "[log]", StringComparison.OrdinalIgnoreCase);
                continue;
            }

            if (!inLogSection)
            {
                continue;
            }

            if (trimmed.StartsWith("level=", StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(trimmed, "level=WARNING", StringComparison.OrdinalIgnoreCase))
            {
                lines[index] = "level=WARNING";
                changed = true;
            }
            else if (trimmed.StartsWith("toFile=", StringComparison.OrdinalIgnoreCase) &&
                     !string.Equals(trimmed, "toFile=false", StringComparison.OrdinalIgnoreCase))
            {
                lines[index] = "toFile=false";
                changed = true;
            }
        }

        if (changed)
        {
            File.WriteAllLines(path, lines);
        }
    }
}

internal sealed class DeskflowServerController : IDisposable
{
    private readonly Process? _ownedProcess;

    private DeskflowServerController(
        string statusText,
        bool isAvailable,
        Process? ownedProcess = null)
    {
        StatusText = statusText;
        IsAvailable = isAvailable;
        _ownedProcess = ownedProcess;
    }

    public string StatusText { get; }
    public bool IsAvailable { get; }

    public static DeskflowServerController Unavailable(string statusText) => new(statusText, false);

    public static DeskflowServerController StartOrAttach(
        string executable,
        string coreSettings,
        string serverConfiguration)
    {
        foreach (var process in Process.GetProcessesByName("deskflow-core"))
        {
            try
            {
                if (string.Equals(process.MainModule?.FileName, executable, StringComparison.OrdinalIgnoreCase))
                {
                    process.Dispose();
                    return new DeskflowServerController("Input sharing: connected bridge ready", true);
                }
            }
            catch
            {
                // Processes owned by another account may not expose their image path.
            }
            finally
            {
                process.Dispose();
            }
        }

        var startInfo = new ProcessStartInfo
        {
            FileName = executable,
            UseShellExecute = false,
            CreateNoWindow = true,
            WorkingDirectory = Path.GetDirectoryName(executable) ?? Environment.CurrentDirectory
        };
        startInfo.ArgumentList.Add("server");
        startInfo.ArgumentList.Add("--settings");
        startInfo.ArgumentList.Add(coreSettings);

        // The external config is referenced by Deskflow.conf. Touching it here
        // also makes a missing or unwritable configuration fail before launch.
        _ = File.GetLastWriteTimeUtc(serverConfiguration);

        var processStarted = Process.Start(startInfo)
            ?? throw new InvalidOperationException("Deskflow did not start.");
        return new DeskflowServerController("Input sharing: connected bridge ready", true, processStarted);
    }

    public void Dispose()
    {
        if (_ownedProcess is null)
        {
            return;
        }

        try
        {
            if (!_ownedProcess.HasExited)
            {
                _ownedProcess.Kill(entireProcessTree: true);
                _ownedProcess.WaitForExit(2000);
            }
        }
        catch
        {
            // Windows shutdown or a manual Deskflow stop may win the race.
        }
        finally
        {
            _ownedProcess.Dispose();
        }
    }
}
