using System.Diagnostics;
using System.Net;
using System.Net.NetworkInformation;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;

namespace Moniswitch;

internal static partial class DeskflowBridge
{
    [GeneratedRegex(@"[^A-Za-z0-9._-]")]
    private static partial Regex UnsafeScreenNameCharacters();

    public static string? FindExecutable()
    {
        var candidates = new[]
        {
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "Deskflow", "deskflow-core.exe"),
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Programs", "Deskflow", "deskflow-core.exe"),
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Deskflow", "deskflow-core.exe")
        };

        return candidates.FirstOrDefault(File.Exists);
    }

    public static string GenerateServerConfiguration(
        string windowsScreenName,
        string linuxScreenName,
        HotkeyBinding hotkey)
    {
        var windows = SanitizeScreenName(windowsScreenName, "windows-pc");
        var linux = SanitizeScreenName(linuxScreenName, "linux-pc");

        // F23 and F24 are internal, modifier-free control signals sent only
        // after the user's public shortcut is fully released. Explicit screen
        // targets cannot drift out of sync after either computer restarts.
        var text = new StringBuilder();
        text.AppendLine("# Generated by Moniswitch. Deskflow remains a separate GPL-2.0 program.");
        text.AppendLine("section: screens");
        text.AppendLine($"    {windows}:");
        text.AppendLine($"    {linux}:");
        text.AppendLine("end");
        text.AppendLine();
        text.AppendLine("section: options");
        text.AppendLine("    heartbeat = 3000");
        text.AppendLine("    switchDelay = 250");
        // Waynergy 0.0.17 can lose framing on newer multi-format clipboard
        // payloads. Keep the control channel input-only so clipboard data can
        // never take keyboard and mouse down with it.
        text.AppendLine("    clipboardSharing = false");
        text.AppendLine(
            $"    keystroke({hotkey.DeskflowLocalCommandText}) = switchToScreen({windows})");
        text.AppendLine(
            $"    keystroke({hotkey.DeskflowRemoteCommandText}) = switchToScreen({linux})");
        text.AppendLine("end");
        return text.ToString();
    }

    public static string WriteServerConfiguration(
        string directoryPath,
        string windowsScreenName,
        string linuxScreenName,
        HotkeyBinding hotkey)
    {
        Directory.CreateDirectory(directoryPath);
        var path = Path.Combine(directoryPath, "deskflow-server.conf");
        File.WriteAllText(path, GenerateServerConfiguration(windowsScreenName, linuxScreenName, hotkey));
        return path;
    }

    public static DeskflowServerController? StartServerIfEnabled(
        InputSharingSettings settings,
        string settingsDirectory,
        HotkeyBinding hotkey)
    {
        if (!settings.Enabled)
        {
            return null;
        }

        try
        {
            var executable = settings.DeskflowExecutablePath;
            if (string.IsNullOrWhiteSpace(executable) || !File.Exists(executable))
            {
                executable = FindExecutable();
            }

            if (string.IsNullOrWhiteSpace(executable))
            {
                return DeskflowServerController.Unavailable("Input sharing: Deskflow not found");
            }

            var deskflowDirectory = Path.Combine(settingsDirectory, "deskflow");
            var serverConfiguration = WriteServerConfiguration(
                deskflowDirectory,
                settings.WindowsScreenName,
                settings.LinuxScreenName,
                hotkey);
            var coreSettings = Path.Combine(deskflowDirectory, "Deskflow.conf");
            EnsureCoreSettings(coreSettings, deskflowDirectory, settings.WindowsScreenName, serverConfiguration);
            OptimizeCoreSettings(coreSettings);
            return DeskflowServerController.StartOrAttach(executable, coreSettings, serverConfiguration,
                SanitizeScreenName(settings.WindowsScreenName, "windows-pc"),
                SanitizeScreenName(settings.LinuxScreenName, "linux-pc"));
        }
        catch (Exception exception)
        {
            return DeskflowServerController.Unavailable($"Input sharing: {exception.Message}");
        }
    }

    public static string? TryGetServerFingerprint(string settingsDirectory)
    {
        var certificatePath = Path.Combine(settingsDirectory, "deskflow", "tls", "deskflow.pem");
        if (!File.Exists(certificatePath))
        {
            return null;
        }

        try
        {
            using var certificate = X509Certificate2.CreateFromPemFile(certificatePath);
            return certificate.GetCertHashString(HashAlgorithmName.SHA256);
        }
        catch
        {
            return null;
        }
    }

    private static string SanitizeScreenName(string value, string fallback)
    {
        var sanitized = UnsafeScreenNameCharacters().Replace(value.Trim(), "-");
        return string.IsNullOrWhiteSpace(sanitized) ? fallback : sanitized;
    }

    internal static void EnsureCoreSettings(
        string coreSettings,
        string deskflowDirectory,
        string windowsScreenName,
        string serverConfiguration)
    {
        if (File.Exists(coreSettings))
        {
            return;
        }

        var tlsDirectory = Path.Combine(deskflowDirectory, "tls");
        var certificatePath = Path.Combine(tlsDirectory, "deskflow.pem");
        Directory.CreateDirectory(tlsDirectory);
        if (!File.Exists(certificatePath))
        {
            WriteCertificate(certificatePath);
        }

        var windows = SanitizeScreenName(windowsScreenName, "windows-pc");
        var certificate = IniPath(certificatePath);
        var serverConfig = IniPath(serverConfiguration);
        var logPath = IniPath(Path.Combine(deskflowDirectory, "deskflow-server.log"));
        var text = new StringBuilder();
        text.AppendLine("[core]");
        text.AppendLine($"computerName={windows}");
        text.AppendLine("coreMode=2");
        text.AppendLine("port=24800");
        text.AppendLine("processMode=1");
        text.AppendLine("startedBefore=true");
        text.AppendLine("useHooks=true");
        text.AppendLine();
        text.AppendLine("[gui]");
        text.AppendLine("autoHide=true");
        text.AppendLine("closeToTray=true");
        text.AppendLine("enableUpdateCheck=false");
        text.AppendLine();
        text.AppendLine("[log]");
        text.AppendLine($"file={logPath}");
        text.AppendLine("level=INFO");
        text.AppendLine("toFile=false");
        text.AppendLine();
        text.AppendLine("[security]");
        text.AppendLine($"certificate={certificate}");
        // Waynergy pins this server certificate. Client-fingerprint prompts
        // require Deskflow's GUI, so the headless server accepts the configured
        // client on the trusted LAN instead of adding another resident process.
        text.AppendLine("checkPeerFingerprints=false");
        text.AppendLine("keySize=3072");
        text.AppendLine("tlsEnabled=true");
        text.AppendLine();
        text.AppendLine("[server]");
        text.AppendLine("externalConfig=true");
        text.AppendLine($"externalConfigFile={serverConfig}");
        text.AppendLine("protocol=barrier");
        File.WriteAllText(coreSettings, text.ToString());
    }

    private static void WriteCertificate(string path)
    {
        using var rsa = RSA.Create(3072);
        var request = new CertificateRequest(
            "CN=Moniswitch Deskflow",
            rsa,
            HashAlgorithmName.SHA256,
            RSASignaturePadding.Pkcs1);
        request.CertificateExtensions.Add(
            new X509BasicConstraintsExtension(false, false, 0, critical: false));
        request.CertificateExtensions.Add(
            new X509KeyUsageExtension(
                X509KeyUsageFlags.DigitalSignature | X509KeyUsageFlags.KeyEncipherment,
                critical: true));
        request.CertificateExtensions.Add(
            new X509SubjectKeyIdentifierExtension(request.PublicKey, critical: false));

        using var certificate = request.CreateSelfSigned(
            DateTimeOffset.UtcNow.AddDays(-1),
            DateTimeOffset.UtcNow.AddYears(10));
        File.WriteAllText(
            path,
            rsa.ExportPkcs8PrivateKeyPem() + Environment.NewLine + certificate.ExportCertificatePem());
    }

    private static string IniPath(string path) => path.Replace('\\', '/');

    internal static void OptimizeCoreSettings(string path)
    {
        var lines = File.ReadAllLines(path).ToList();
        var inLogSection = false;
        var inSecuritySection = false;
        var inServerSection = false;
        var foundSecuritySection = false;
        var foundCheckPeerFingerprints = false;
        var foundTlsEnabled = false;
        var foundServerSection = false;
        var foundServerProtocol = false;
        var changed = false;

        for (var index = 0; index < lines.Count; index++)
        {
            var trimmed = lines[index].Trim();
            if (trimmed.StartsWith('[') && trimmed.EndsWith(']'))
            {
                if (inSecuritySection)
                {
                    if (!foundCheckPeerFingerprints)
                    {
                        lines.Insert(index++, "checkPeerFingerprints=false");
                        changed = true;
                    }

                    if (!foundTlsEnabled)
                    {
                        lines.Insert(index++, "tlsEnabled=true");
                        changed = true;
                    }

                    trimmed = lines[index].Trim();
                }

                if (inServerSection && !foundServerProtocol)
                {
                    lines.Insert(index++, "protocol=barrier");
                    changed = true;
                    trimmed = lines[index].Trim();
                }

                inLogSection = string.Equals(trimmed, "[log]", StringComparison.OrdinalIgnoreCase);
                inSecuritySection = string.Equals(trimmed, "[security]", StringComparison.OrdinalIgnoreCase);
                inServerSection = string.Equals(trimmed, "[server]", StringComparison.OrdinalIgnoreCase);
                foundSecuritySection |= inSecuritySection;
                foundServerSection |= inServerSection;
                continue;
            }

            if (inSecuritySection)
            {
                if (trimmed.StartsWith("checkPeerFingerprints=", StringComparison.OrdinalIgnoreCase))
                {
                    foundCheckPeerFingerprints = true;
                    if (!string.Equals(
                            trimmed,
                            "checkPeerFingerprints=false",
                            StringComparison.OrdinalIgnoreCase))
                    {
                        lines[index] = "checkPeerFingerprints=false";
                        changed = true;
                    }
                }
                else if (trimmed.StartsWith("tlsEnabled=", StringComparison.OrdinalIgnoreCase))
                {
                    foundTlsEnabled = true;
                    if (!string.Equals(trimmed, "tlsEnabled=true", StringComparison.OrdinalIgnoreCase))
                    {
                        lines[index] = "tlsEnabled=true";
                        changed = true;
                    }
                }
            }

            if (inServerSection && trimmed.StartsWith("protocol=", StringComparison.OrdinalIgnoreCase))
            {
                foundServerProtocol = true;
                if (!string.Equals(trimmed, "protocol=barrier", StringComparison.OrdinalIgnoreCase))
                {
                    lines[index] = "protocol=barrier";
                    changed = true;
                }
            }

            if (inLogSection)
            {
                if (trimmed.StartsWith("level=", StringComparison.OrdinalIgnoreCase) &&
                    !string.Equals(trimmed, "level=INFO", StringComparison.OrdinalIgnoreCase))
                {
                    lines[index] = "level=INFO";
                    changed = true;
                }
                else if (trimmed.StartsWith("toFile=", StringComparison.OrdinalIgnoreCase) &&
                         !string.Equals(trimmed, "toFile=false", StringComparison.OrdinalIgnoreCase))
                {
                    lines[index] = "toFile=false";
                    changed = true;
                }
            }
        }

        if (inSecuritySection)
        {
            if (!foundCheckPeerFingerprints)
            {
                lines.Add("checkPeerFingerprints=false");
                changed = true;
            }

            if (!foundTlsEnabled)
            {
                lines.Add("tlsEnabled=true");
                changed = true;
            }
        }
        else if (!foundSecuritySection)
        {
            lines.Add(string.Empty);
            lines.Add("[security]");
            lines.Add("checkPeerFingerprints=false");
            lines.Add("tlsEnabled=true");
            changed = true;
        }

        if (inServerSection && !foundServerProtocol)
        {
            lines.Add("protocol=barrier");
            changed = true;
        }
        else if (!foundServerSection)
        {
            lines.Add(string.Empty);
            lines.Add("[server]");
            lines.Add("protocol=barrier");
            changed = true;
        }

        if (changed)
        {
            File.WriteAllLines(path, lines);
        }
    }
}

internal sealed class DeskflowServerController : IDisposable
{
    private const int ServerPort = 24800;
    private const uint InputKeyboard = 1;
    private const uint KeyEventKeyUp = 0x0002;
    private const ushort VirtualKeyF23 = 0x86;
    private const ushort VirtualKeyF24 = 0x87;
    private readonly Process? _process;
    private readonly bool _ownsProcess;
    private IPEndPoint? _connectedClient;
    private DateTime? _connectedSinceUtc;
    private volatile string? _activeScreen;
    private string _localScreen = "";
    private string _remoteScreen = "";

    private DeskflowServerController(
        string statusText,
        bool isAvailable,
        Process? process = null,
        bool ownsProcess = false)
    {
        StatusText = statusText;
        IsAvailable = isAvailable;
        _process = process;
        _ownsProcess = ownsProcess;
    }

    public string StatusText { get; }
    public bool IsAvailable { get; }
    public bool IsRemoteActive => _activeScreen == _remoteScreen && _remoteScreen.Length > 0;
    public bool IsClientStable => HasConnectedClient() &&
        _connectedSinceUtc is { } since && DateTime.UtcNow - since >= TimeSpan.FromMilliseconds(750);
    public bool IsRunning
    {
        get
        {
            if (!IsAvailable || _process is null)
            {
                return false;
            }

            try
            {
                return !_process.HasExited;
            }
            catch
            {
                return false;
            }
        }
    }

    public bool HasConnectedClient()
    {
        if (!IsRunning)
        {
            ResetConnectedClient();
            return false;
        }

        try
        {
            var connection = IPGlobalProperties.GetIPGlobalProperties()
                .GetActiveTcpConnections()
                .FirstOrDefault(connection =>
                    connection.LocalEndPoint.Port == ServerPort &&
                    connection.State == TcpState.Established);
            if (connection is null)
            {
                ResetConnectedClient();
                return false;
            }

            if (_connectedClient is null || !_connectedClient.Equals(connection.RemoteEndPoint))
            {
                _connectedClient = connection.RemoteEndPoint;
                _connectedSinceUtc = DateTime.UtcNow;
                // A replacement receiver starts on the server's local screen.
                // Its TCP connection is not a continuation of the old route.
                _activeScreen = _localScreen;
            }

            return true;
        }
        catch (NetworkInformationException)
        {
            ResetConnectedClient();
            return false;
        }
    }

    public async Task<bool> WaitForConnectedClientAsync(TimeSpan timeout)
    {
        var deadline = DateTime.UtcNow + timeout;
        while (DateTime.UtcNow < deadline)
        {
            if (!IsRunning)
            {
                return false;
            }

            if (HasConnectedClient() &&
                _connectedSinceUtc is { } connectedSince &&
                DateTime.UtcNow - connectedSince >= TimeSpan.FromMilliseconds(750))
            {
                return true;
            }

            await Task.Delay(150);
        }

        return HasConnectedClient() &&
               _connectedSinceUtc is { } finalConnectedSince &&
               DateTime.UtcNow - finalConnectedSince >= TimeSpan.FromMilliseconds(750);
    }

    private void ResetConnectedClient()
    {
        _connectedClient = null;
        _connectedSinceUtc = null;
        _activeScreen = _localScreen;
    }

    public async Task SetInputTargetAsync(bool remote, bool force = false)
    {
        if (!IsRunning)
        {
            throw new InvalidOperationException("The Deskflow bridge is not running.");
        }

        var target = remote ? _remoteScreen : _localScreen;
        if (!force && _activeScreen == target)
        {
            return;
        }

        var virtualKey = remote ? VirtualKeyF24 : VirtualKeyF23;
        var inputs = new[]
        {
            KeyboardEvent(virtualKey, 0),
            KeyboardEvent(virtualKey, KeyEventKeyUp)
        };
        var sent = SendInput((uint)inputs.Length, inputs, Marshal.SizeOf<Input>());
        if (sent != inputs.Length)
        {
            throw new System.ComponentModel.Win32Exception(
                Marshal.GetLastWin32Error(),
                "Windows could not send the private Deskflow handoff signal.");
        }

        var deadline = DateTime.UtcNow.AddSeconds(3);
        while (IsRunning && DateTime.UtcNow < deadline)
        {
            if (_activeScreen == target)
            {
                return;
            }
            await Task.Delay(30);
        }
        throw new InvalidOperationException("The input bridge did not confirm the handoff. The monitor was not changed.");
    }

    internal void ObserveStatus(string? line)
    {
        if (line is null) return;
        if (line.Contains("entering screen", StringComparison.Ordinal))
        {
            _activeScreen = _localScreen;
        }
        if (line.Contains("switch from \"", StringComparison.Ordinal))
        {
            if (line.Contains($" to \"{_remoteScreen}\" at ", StringComparison.Ordinal))
                _activeScreen = _remoteScreen;
            else if (line.Contains($" to \"{_localScreen}\" at ", StringComparison.Ordinal))
                _activeScreen = _localScreen;
        }
    }

    private static Input KeyboardEvent(ushort virtualKey, uint flags) => new()
    {
        Type = InputKeyboard,
        Data = new InputUnion
        {
            Keyboard = new KeyboardInput
            {
                VirtualKey = virtualKey,
                Flags = flags,
                ExtraInfo = GetMessageExtraInfo()
            }
        }
    };

    public static DeskflowServerController Unavailable(string statusText) => new(statusText, false);

    public static DeskflowServerController StartOrAttach(
        string executable,
        string coreSettings,
        string serverConfiguration,
        string localScreen,
        string remoteScreen)
    {
        foreach (var process in Process.GetProcessesByName("deskflow-core"))
        {
            try
            {
                if (string.Equals(process.MainModule?.FileName, executable, StringComparison.OrdinalIgnoreCase))
                {
                    throw new InvalidOperationException(
                        "Close the existing Deskflow server, then restart input sharing so the correct handoff configuration can load.");
                }
            }
            catch (System.ComponentModel.Win32Exception)
            {
                // Processes owned by another account may not expose their image path.
            }
            finally
            {
                process.Dispose();
            }
        }

        var startInfo = new ProcessStartInfo
        {
            FileName = executable,
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            WorkingDirectory = Path.GetDirectoryName(executable) ?? Environment.CurrentDirectory
        };
        startInfo.ArgumentList.Add("server");
        startInfo.ArgumentList.Add("--settings");
        startInfo.ArgumentList.Add(coreSettings);

        // The external config is referenced by Deskflow.conf. Touching it here
        // also makes a missing or unwritable configuration fail before launch.
        _ = File.GetLastWriteTimeUtc(serverConfiguration);

        var processStarted = new Process { StartInfo = startInfo };
        var controller = new DeskflowServerController(
            "Input sharing: bridge ready",
            true,
            processStarted,
            ownsProcess: true)
        {
            _localScreen = localScreen,
            _remoteScreen = remoteScreen,
            _activeScreen = localScreen
        };
        processStarted.OutputDataReceived += (_, args) => controller.ObserveStatus(args.Data);
        processStarted.ErrorDataReceived += (_, args) => controller.ObserveStatus(args.Data);
        if (!processStarted.Start()) throw new InvalidOperationException("Deskflow did not start.");
        processStarted.BeginOutputReadLine();
        processStarted.BeginErrorReadLine();
        return controller;
    }

    public void Dispose()
    {
        if (_process is null)
        {
            return;
        }

        try
        {
            if (_ownsProcess && !_process.HasExited)
            {
                _process.Kill(entireProcessTree: true);
                _process.WaitForExit(2000);
            }
        }
        catch
        {
            // Windows shutdown or a manual Deskflow stop may win the race.
        }
        finally
        {
            _process.Dispose();
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct Input
    {
        public uint Type;
        public InputUnion Data;
    }

    [StructLayout(LayoutKind.Explicit)]
    private struct InputUnion
    {
        [FieldOffset(0)] public MouseInput Mouse;
        [FieldOffset(0)] public KeyboardInput Keyboard;
        [FieldOffset(0)] public HardwareInput Hardware;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct MouseInput
    {
        public int X;
        public int Y;
        public uint MouseData;
        public uint Flags;
        public uint Time;
        public UIntPtr ExtraInfo;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct KeyboardInput
    {
        public ushort VirtualKey;
        public ushort ScanCode;
        public uint Flags;
        public uint Time;
        public UIntPtr ExtraInfo;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct HardwareInput
    {
        public uint Message;
        public ushort ParameterLow;
        public ushort ParameterHigh;
    }

    [DllImport("user32.dll", SetLastError = true)]
    private static extern uint SendInput(uint inputCount, Input[] inputs, int inputSize);

    [DllImport("user32.dll")]
    private static extern UIntPtr GetMessageExtraInfo();
}
